blank_issues_enabled: false

contact_links:
  - name: （中文）阅读 Wiki
    url: https://merlinkodo.github.io/clash-rev-doc/zh_CN/
    about: 如果你是新手，或者想要了解 Clash.Rev 的更多信息，请阅读我们撰写的官方 Wiki
  - name: (English) Read our Wiki page
    url: https://merlinkodo.github.io/clash-rev-doc/
    about: If you are new to Clash.Rev, or want to know more about Clash.Rev, please read our Wiki page
